services:
  postgres:
    container_name: quad_dash_db
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=quad_dash
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: