@baseUrl = http://localhost:3000
GET {{baseUrl}}/

###
POST {{baseUrl}}/companies
Content-Type: application/json

{
   "companyName": "Quad Store 2",
   "managerName": "Doe John",
   "email": "email_2@quad.com",
   "phone": "1234567890"
}
###
POST {{baseUrl}}/authenticate
Content-Type: application/json

{
   "email": "email_2@quad.com"
}